/* eslint-disable @typescript-eslint/prefer-ts-expect-error */
/* eslint-disable @typescript-eslint/ban-ts-comment */

import { promises } from 'fs';

import chalk from 'chalk';
import openapiTS, { OpenAPITSOptions } from 'openapi-typescript';

import { transform, postTransform } from './transform.mjs';

const URL_SCHEMA_PET_STORE =
  'https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml';

const OPENAPI_TS_OPTIONS: OpenAPITSOptions = {
  immutableTypes: true,
  exportType: true,
  transform,
  postTransform,
  commentHeader: `
  /**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

  /* eslint-disable */
  `,
  inject: `
  type PetMonth = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  export type PetDate = \`Y\${number}-M\${PetMonth}}\`
  `,
};

try {
  // @ts-ignore - Top-level await used only in Node.js
  const generatedOutput = await openapiTS(URL_SCHEMA_PET_STORE, OPENAPI_TS_OPTIONS);

  const GENERATED_API_TYPES_PATH = './src/common/api/petstore/api-types/index.ts';
  // @ts-ignore - Top-level await used only in Node.js
  await promises.writeFile(GENERATED_API_TYPES_PATH, generatedOutput);

  console.log(chalk.blue('API types updated successfully!'));
} catch (error) {
  console.log(chalk.red('Error occurred while trying to update API types.'));
  console.log(chalk.red(error));
}
